/* anim.js — one paused GSAP timeline, built synchronously at load.
 *
 * Every entrance time is CUE.<name>, generated by build-cues.mjs straight from
 * ../audio/narration.words.json, so a visual can only land on the word it was
 * storyboarded to land on. Times not in CUE are the storyboard's own
 * closing-beat / transition seconds, which sit inside spoken silences.
 *
 * Motion follows tokens.yml motion:  entrance 0.4-0.6s (whole entrance settles
 * by 1.2s), stagger 0.12-0.18s, one closing beat per scene, no repeat:-1, and
 * motion.exit-group — an element leaving a scene and the text it carries are a
 * single tween target, never two.
 */
window.buildLessonTimeline = function () {
  var C = window.CUE;
  var B = window.BEATS; // [[start, duration], ...] index 0 = beat 1
  var tl = gsap.timeline({ paused: true });

  // token colors — the only color literals in the motion layer
  var NAVY = "#0d2437",
    BLUE = "#3393d6",
    GOLD = "#eaab2d",
    PAPER = "#ffffff",
    BORDER = "#cccedf",
    MUTED = "#5f6f96";

  // the two rail-marker states (tokens components.step-node: gold fill on
  // activation, navy number; spent markers fall back to the blue outline chip)
  var LIVE = { backgroundColor: GOLD, borderColor: NAVY, color: NAVY };
  var SPENT = { backgroundColor: PAPER, borderColor: BLUE, color: BLUE };

  var EASE = "power3.out";
  var D = 0.5; // entrance duration, inside the 0.4-0.6s band
  var STAG = 0.14; // inside the 0.12-0.18s band

  function start(n) {
    return B[n - 1][0];
  }
  function hide(sel, at, vars) {
    tl.set(sel, Object.assign({ opacity: 0 }, vars || {}), at);
  }
  function rise(sel, at, vars) {
    vars = vars || {};
    tl.fromTo(
      sel,
      { y: vars.y === undefined ? 24 : vars.y, opacity: 0 },
      {
        y: 0,
        opacity: vars.opacity === undefined ? 1 : vars.opacity,
        duration: vars.d || D,
        ease: vars.ease || EASE,
        stagger: vars.stagger || 0,
      },
      at,
    );
  }
  function pop(sel, at, vars) {
    vars = vars || {};
    tl.fromTo(
      sel,
      { scale: 0.9, opacity: 0 },
      { scale: 1, opacity: 1, duration: vars.d || 0.45, ease: "back.out(1.4)", stagger: vars.stagger || 0 },
      at,
    );
  }
  function draw(sel, at, d) {
    tl.fromTo(sel, { scaleX: 0 }, { scaleX: 1, duration: d || D, ease: "power2.out" }, at);
  }
  function drawV(sel, at, d) {
    tl.fromTo(sel, { scaleY: 0 }, { scaleY: 1, duration: d || D, ease: "power2.out" }, at);
  }
  function slideIn(sel, at, from) {
    tl.fromTo(sel, { x: from, opacity: 0 }, { x: 0, opacity: 1, duration: 0.55, ease: EASE }, at);
  }
  function state(sel, at, s, d) {
    tl.to(sel, Object.assign({ duration: d || 0.45 }, s), at);
  }

  /* ── CHROME — the progress rail fills across the whole runtime ────────── */
  tl.fromTo("#rail-fill", { scaleX: 0 }, { scaleX: 1, duration: 146.5, ease: "none" }, 0);

  /* ── BEAT 1 — series title lockup ─────────────────────────────────────── */
  hide("#b1-eyebrow, #b1-title .w", 0);
  tl.set("#b1-rings", { opacity: 0 }, 0);
  tl.set("#b1-rule", { scaleX: 0 }, 0);
  rise("#b1-eyebrow", 0.02, { y: 16, d: 0.45 });
  tl.to("#b1-rings", { opacity: 0.35, duration: 0.6, ease: "power2.out" }, 0.2);
  rise("#b1-title .w", 0.05, { y: 24, d: 0.45, stagger: 0.12 }); // settles at 1.22s
  draw("#b1-rule", 1.6, 0.5); // closing beat 2.1: the gold rule completes

  /* ── BEAT 2 — the navy field pushes up, paper rises ───────────────────── */
  var s2 = start(2);
  tl.set("#b2-navy", { yPercent: 0 }, s2);
  tl.set("#b2-paper", { yPercent: 100 }, s2);
  hide("#b2-l1, #b2-l2, #b2-c1, #b2-c2", s2);
  tl.to("#b2-navy", { yPercent: -100, duration: 0.6, ease: "power3.inOut" }, s2);
  tl.to("#b2-paper", { yPercent: 0, duration: 0.6, ease: "power3.inOut" }, s2);
  rise("#b2-l1", C.b2_career, { y: 20 });
  rise("#b2-l2", C.b2_title, { y: 20 });
  pop("#b2-c1", C.b2_intern);
  pop("#b2-c2", C.b2_analyst);

  /* ── BEAT 3 — the remaining three chips wrap to row two ───────────────── */
  var s3 = start(3);
  hide("#b3-c3, #b3-c4, #b3-c5", s3);
  pop("#b3-c3", C.b3_coordinator);
  tl.to("#b3-c3", { y: -10, duration: 0.3 }, C.b3_coordinator + 0.3);
  pop("#b3-c4", C.b3_assistant);
  tl.to("#b3-c4", { y: 8, duration: 0.3 }, C.b3_assistant + 0.3);
  pop("#b3-c5", C.b3_associate);
  tl.to("#b3-c5", { y: -8, duration: 0.3 }, C.b3_associate + 0.3);
  // closing beat 10.9: the five chips settle onto one shared baseline
  tl.to("#b3-c3, #b3-c4, #b3-c5", { y: 0, duration: 0.55, ease: "power2.out" }, 10.9);

  /* ── BEAT 4 — chips drain to the thesis ───────────────────────────────── */
  var s4 = start(4);
  hide("#b4-quote, #b4-leadin, #b4-f1, #b4-f2, #b4-f3", s4);
  tl.set("#b4-rule", { scaleX: 0 }, s4);
  tl.set(".b4-chip", { borderColor: BLUE, color: BLUE, y: 0, borderRadius: 100 }, s4);
  // 13.13 "labels." — the chips drain to a hairline outline
  tl.to(".b4-chip", { borderColor: BORDER, color: MUTED, duration: 0.6, ease: "power2.out" }, C.b4_labels);
  rise("#b4-quote", C.b4_labels, { y: 20 });
  draw("#b4-rule", C.b4_labels, 0.75); // the video's only rule-wipe row
  // 14.06 "They" — the governing lead-in types in
  var leadin = document.getElementById("b4-leadin");
  var leadinW = leadin.scrollWidth + 4;
  tl.set(leadin, { opacity: 1, width: 0, overflow: "hidden", whiteSpace: "nowrap" }, C.b4_they);
  tl.to(leadin, { width: leadinW, duration: 0.75, ease: "none" }, C.b4_they);
  rise("#b4-f1", C.b4_how, { y: 18 });
  rise("#b4-f2", C.b4_what, { y: 18 });
  rise("#b4-f3", C.b4_where, { y: 18 });
  // closing beat 19.5: the last chip drops out of the row as a flat tag. One
  // tween, one target — the chip carries its word with it (motion.exit-group).
  tl.to("#b4-peel", { y: 40, borderRadius: 8, duration: 0.5, ease: "power2.out" }, 19.5);

  /* ── BEAT 5 — the tinted ground splits, the left half fills navy ──────── */
  var s5 = start(5);
  tl.set("#b5-half", { scaleX: 0, transformOrigin: "right center" }, s5);
  tl.set("#b5-seam", { scaleY: 0 }, s5);
  hide("#b5-figure, #b5-l1, #b5-l2", s5);
  tl.set("#b5-underline", { scaleX: 0 }, s5);
  tl.to("#b5-seam", { scaleY: 1, duration: 0.5, ease: "power3.inOut" }, C.b5_before);
  tl.to("#b5-half", { scaleX: 1, duration: 0.6, ease: "power3.inOut" }, C.b5_before + 0.1);
  rise("#b5-figure", C.b5_before + 0.9, { y: 22, d: 0.6 });
  rise("#b5-l1", C.b5_understand, { y: 22 });
  rise("#b5-l2", C.b5_that, { y: 22 });
  draw("#b5-underline", C.b5_patterns, 0.54); // closing beat 27.5

  /* ── BEAT 6 — the seam sweeps right, six cards deal in ────────────────── */
  var s6 = start(6);
  tl.set("#b6-navy, #b6-seam", { x: 0 }, s6);
  hide(".b6-slot", s6);
  hide(".b6-card", s6, { scale: 0.9 });
  tl.set(".b6-glyph", { color: NAVY }, s6);
  tl.to("#b6-navy, #b6-seam", { x: 1920, duration: 0.75, ease: "power3.inOut" }, C.b6_think);
  tl.to(".b6-slot", { opacity: 1, duration: 0.4, stagger: 0.05, ease: "power2.out" }, C.b6_think + 0.45);
  var b6cards = ["#b6-k1", "#b6-k2", "#b6-k3", "#b6-k4", "#b6-k5", "#b6-k6"];
  var b6cues = [C.b6_school, C.b6_parttime, C.b6_internships, C.b6_student, C.b6_volunteering, C.b6_personal];
  b6cards.forEach(function (sel, i) {
    pop(sel, b6cues[i]);
  });
  // closing beat 35.98: the six glyphs brighten together, to gold
  tl.to(".b6-glyph", { color: GOLD, duration: 0.4, ease: "power2.out" }, 35.98);

  /* ── BEAT 7 — blue floods in radially, four questions stack ───────────── */
  var s7 = start(7);
  tl.set("#b7-flood", { scale: 0 }, s7);
  hide("#b7-panel", s7, { scale: 0.96 });
  hide("#b7-q1, #b7-q2, #b7-q3, #b7-q4", s7, { x: 0 });
  tl.to("#b7-flood", { scale: 1, duration: 0.45, ease: "power3.inOut" }, s7);
  tl.to("#b7-panel", { opacity: 1, scale: 1, duration: 0.5, ease: EASE }, s7 + 0.12);
  var b7q = ["#b7-q1", "#b7-q2", "#b7-q3", "#b7-q4"];
  var b7cues = [Math.max(C.b7_q1, s7 + 0.15), C.b7_q2, C.b7_q3, C.b7_q4];
  b7q.forEach(function (sel, i) {
    rise(sel, b7cues[i], { y: 22 });
    // the spent question recedes as a whole row — marker and line together —
    // so the eye stays on the live one (motion.exit-group)
    if (i > 0) tl.to(b7q[i - 1], { opacity: 0.45, duration: 0.45 }, b7cues[i]);
  });
  tl.to(b7q.join(", "), { opacity: 1, duration: 0.5 }, 43.6); // closing beat

  /* ── BEAT 8 — the paper ground wipes down, the balance scale tips ─────── */
  var s8 = start(8);
  tl.set("#b8-paper", { scaleY: 0, transformOrigin: "top center" }, s8);
  hide("#b8-scale, #b8-h1, #b8-h2", s8);
  tl.set("#b8-beam", { rotation: 0 }, s8);
  tl.set("#b8-d1, #b8-d2, #b8-d3", { opacity: 0.25 }, s8);
  tl.to("#b8-paper", { scaleY: 1, duration: 0.6, ease: "power3.inOut" }, s8);
  rise("#b8-scale", s8 + 0.35, { y: 22, d: 0.6 });
  rise("#b8-h1", C.b8_moments, { y: 20 });
  rise("#b8-h2", C.b8_than, { y: 20 });
  tl.to("#b8-beam", { rotation: 7, duration: 0.7, ease: "power2.out" }, C.b8_reveal);
  tl.to("#b8-d1", { opacity: 1, duration: 0.4 }, C.b8_show);
  tl.to("#b8-d2", { opacity: 1, duration: 0.4 }, C.b8_naturally);
  tl.to("#b8-d3", { opacity: 1, duration: 0.4 }, C.b8_naturally + 0.54);
  tl.to("#b8-beam", { rotation: 5, duration: 0.6, ease: "power2.inOut" }, 50.9); // closing beat

  /* ── BEAT 9 — diptych: organizing / analyzing ─────────────────────────── */
  var s9 = start(9);
  hide("#b9-p1, #b9-p2, #b9-c1, #b9-c2", s9);
  tl.set("#b9-s1", { x: -30, y: 40, rotation: -12 }, s9);
  tl.set("#b9-s2", { x: 20, y: -50, rotation: 9 }, s9);
  tl.set("#b9-s3", { x: -14, y: 56, rotation: 14 }, s9);
  tl.set("#b9-s4", { x: 34, y: -34, rotation: -8 }, s9);
  tl.set("#b9-trend", { opacity: 0, scaleX: 0, transformOrigin: "left center" }, s9);
  slideIn("#b9-p1", C.b9_left, -40);
  rise("#b9-c1", C.b9_organizing, { y: 18 });
  tl.to("#b9-s1, #b9-s2, #b9-s3, #b9-s4", { x: 0, y: 0, rotation: 0, duration: 0.85, ease: "power3.out", stagger: 0.14 }, C.b9_organizing);
  slideIn("#b9-p2", C.b9_right, -40);
  rise("#b9-c2", C.b9_analyzing, { y: 18 });
  tl.to("#b9-trend", { opacity: 1, scaleX: 1, duration: 0.6, ease: "power2.out" }, C.b9_patterns);

  /* ── BEAT 10 — diptych: helping / turning ideas into action ───────────── */
  var s10 = start(10);
  hide("#b10-p1, #b10-p2, #b10-c1, #b10-c2", s10);
  tl.set("#b10-ray1, #b10-ray2", { opacity: 0 }, s10);
  tl.set("#b10-arrow", { opacity: 0, x: -40 }, s10);
  tl.set("#b10-cloud", { opacity: 1 }, s10);
  tl.set("#b10-u1, #b10-u2", { scaleX: 0 }, s10);
  slideIn("#b10-p1", C.b10_left, -40);
  rise("#b10-c1", C.b10_helping, { y: 18 });
  tl.to("#b10-ray1, #b10-ray2", { opacity: 1, duration: 0.4, stagger: 0.16 }, C.b10_helping);
  tl.fromTo("#b10-teacher", { scale: 0.94 }, { scale: 1, duration: 0.6, ease: "back.out(1.4)", transformOrigin: "center center" }, C.b10_helping);
  slideIn("#b10-p2", C.b10_right, -40);
  tl.to("#b10-cloud", { opacity: 0, duration: 0.45, ease: "power2.inOut" }, C.b10_turns);
  tl.to("#b10-arrow", { opacity: 1, duration: 0.45, ease: "power2.out" }, C.b10_turns);
  tl.to("#b10-arrow", { x: 60, duration: 0.5, ease: "power3.out" }, C.b10_action);
  draw("#b10-u1, #b10-u2", 65.0, 0.45); // closing beat

  /* ── BEAT 11 — dots drift together into one path ──────────────────────── */
  var s11 = start(11);
  var b11n = ["#b11-n1", "#b11-n2", "#b11-n3", "#b11-n4", "#b11-n5", "#b11-n6"];
  var b11g = ["#b11-g1", "#b11-g2", "#b11-g3", "#b11-g4", "#b11-g5"];
  hide(b11n.join(", "), s11, { scale: 0.5 });
  tl.set(b11n.join(", "), { backgroundColor: BLUE }, s11);
  hide("#b11-h1, #b11-h2", s11);
  b11g.forEach(function (sel) {
    tl.set(sel, { rotation: Number(document.querySelector(sel).dataset.rot), scaleX: 0 }, s11);
  });
  tl.to(b11n.join(", "), { opacity: 1, scale: 1, duration: 0.5, stagger: STAG, ease: "back.out(1.4)" }, C.b11_a);
  rise("#b11-h1", C.b11_strong, { y: 22 });
  rise("#b11-h2", C.b11_repeated, { y: 22 });
  b11g.forEach(function (sel, i) {
    tl.to(sel, { scaleX: 1, duration: 0.6, ease: "power2.out" }, C.b11_early + i * 0.68);
  });
  // closing beat 70.1: the final node of the path pops, and takes the accent
  tl.to("#b11-n6", { scale: 1.6, backgroundColor: GOLD, duration: 0.22, ease: "power2.out" }, 70.1);
  tl.to("#b11-n6", { scale: 1.25, duration: 0.28, ease: "power2.inOut" }, 70.32);

  /* ── BEAT 12 — the path straightens into a gutter, two quote cards ────── */
  var s12 = start(12);
  var b12g = ["#b12-g1", "#b12-g2", "#b12-g3", "#b12-g4", "#b12-g5"];
  tl.set("#b12-paper", { scaleY: 0, transformOrigin: "top center" }, s12);
  tl.set("#b12-gutter", { scaleY: 0 }, s12);
  hide("#b12-card1, #b12-card2", s12);
  tl.set("#b12-strike", { scaleX: 0 }, s12);
  tl.set("#b12-edge", { scaleY: 0 }, s12);
  b12g.forEach(function (sel) {
    tl.set(sel, { rotation: Number(document.querySelector(sel).dataset.rot), opacity: 1 }, s12);
    tl.to(sel, { rotation: 90, x: 700, y: -60, duration: 1.35, ease: "power2.inOut" }, C.b12_it);
    tl.to(sel, { opacity: 0, duration: 0.4, ease: "power2.in" }, C.b12_it + 1.05);
  });
  tl.to("#b12-paper", { scaleY: 1, duration: 0.55, ease: "power3.inOut" }, C.b12_it + 0.1);
  drawV("#b12-gutter", C.b12_it + 0.5, 0.7);
  rise("#b12-card1", C.b12_this1, { y: 30 });
  draw("#b12-strike", C.b12_path, 0.5);
  rise("#b12-card2", C.b12_this2, { y: 30 });
  drawV("#b12-edge", C.b12_me, 0.5);
  tl.to("#b12-card2", { scale: 1.02, duration: 0.5, ease: "power2.out" }, C.b12_me);
  tl.to("#b12-card1", { opacity: 0.5, duration: 0.5, ease: "power2.out" }, 79.0); // closing beat

  /* ── BEAT 13 — the transitional stat card ─────────────────────────────── */
  var s13 = start(13);
  var num = document.getElementById("b13-num");
  var counter = { v: 0 };
  hide("#b13-label", s13);
  tl.set("#b13-rule", { scaleX: 0, transformOrigin: "center center" }, s13);
  tl.set("#b13-num", { opacity: 0, scale: 0.85 }, s13);
  tl.set(counter, { v: 0 }, s13);
  rise("#b13-label", Math.max(C.b13_in, s13), { y: 18 });
  draw("#b13-rule", Math.max(C.b13_in, s13) + 0.2, 0.5);
  tl.to("#b13-num", { opacity: 1, scale: 1, duration: 0.5, ease: "back.out(1.4)" }, C.b13_three);
  tl.to(
    counter,
    {
      v: 3,
      duration: 0.55,
      ease: "power2.out",
      onUpdate: function () {
        num.textContent = String(Math.round(counter.v));
      },
    },
    C.b13_three,
  );
  tl.to("#b13-label", { scaleX: 1.06, duration: 0.5, ease: "power2.out", transformOrigin: "center center" }, 82.83);

  /* ── BEATS 14-16 — one rail, three states ─────────────────────────────── */
  var s14 = start(14);
  tl.set("#b14-rail", { scaleY: 0 }, s14);
  hide("#b14-m1, #b14-m2, #b14-m3", s14, { scale: 0.6 });
  hide("#b14-panel", s14, { x: 120 });
  hide("#b14-l2", s14);
  drawV("#b14-rail", C.b14_first, 0.6);
  tl.to("#b14-m1, #b14-m2, #b14-m3", { opacity: 1, scale: 1, duration: 0.45, stagger: STAG, ease: "back.out(1.4)" }, C.b14_your);
  slideIn("#b14-panel", C.b14_strengths, 120);
  rise("#b14-l2", C.b14_how, { y: 18 });

  var s15 = start(15);
  tl.set("#b15-m1", LIVE, s15);
  tl.set("#b15-m2", SPENT, s15);
  tl.set("#b15-ghost", { opacity: 1, x: 0 }, s15);
  hide("#b15-panel", s15, { x: 120 });
  hide("#b15-sub", s15);
  hide("#b15-v1, #b15-v2, #b15-v3, #b15-v4, #b15-v5, #b15-v6", s15, { scale: 0.9 });
  state("#b15-m1", C.b15_second, SPENT);
  state("#b15-m2", C.b15_second, LIVE);
  // the spent panel leaves as one unit, its copy travelling inside it
  tl.to("#b15-ghost", { opacity: 0, x: -60, duration: 0.45, ease: "power2.in" }, C.b15_second);
  slideIn("#b15-panel", C.b15_values, 120);
  rise("#b15-sub", C.b15_what, { y: 18 });
  var b15v = ["#b15-v1", "#b15-v2", "#b15-v3", "#b15-v4", "#b15-v5", "#b15-v6"];
  var b15c = [C.b15_learning, C.b15_stability, C.b15_flexibility, C.b15_meaning, C.b15_collaboration, C.b15_recognition];
  b15v.forEach(function (sel, i) {
    tl.to(sel, { opacity: 1, scale: 1, duration: 0.45, ease: "back.out(1.4)" }, b15c[i]);
  });

  var s16 = start(16);
  tl.set("#b16-m1", SPENT, s16);
  tl.set("#b16-m2", LIVE, s16);
  tl.set("#b16-m3", SPENT, s16);
  tl.set("#b16-ghost", { opacity: 1, x: 0 }, s16);
  hide("#b16-panel", s16, { x: 120 });
  tl.set("#b16-bar1", { scaleY: 0, opacity: 0.55 }, s16);
  tl.set("#b16-bar2", { scaleY: 1, backgroundColor: BLUE }, s16);
  state("#b16-m2", C.b16_third, SPENT);
  state("#b16-m3", C.b16_third, LIVE);
  tl.to("#b16-ghost", { opacity: 0, x: -60, duration: 0.45, ease: "power2.in" }, C.b16_third);
  slideIn("#b16-panel", C.b16_energy, 120);
  tl.to("#b16-bar1", { scaleY: 1, opacity: 1, duration: 1.6, ease: "power2.out" }, C.b16_leaves);
  tl.to("#b16-bar2", { scaleY: 0.25, backgroundColor: MUTED, duration: 1.5, ease: "power2.inOut" }, C.b16_consistently);
  // closing beat 105.4: all three markers restore to the live state
  state("#b16-m1, #b16-m2, #b16-m3", 105.4, LIVE);

  /* ── BEAT 17 — the panel collapses, blue irises out, the badge lands ──── */
  var s17 = start(17);
  tl.set("#b17-iris", { scale: 0 }, s17);
  hide("#b17-badge", s17, { scale: 0.9, y: -30 });
  hide("#b17-badge-copy", s17);
  hide("#b17-l2", s17);
  tl.set("#b17-baseline", { scaleX: 0 }, s17);
  tl.to("#b17-iris", { scale: 1, duration: 0.7, ease: "power3.inOut" }, s17);
  tl.to("#b17-badge", { opacity: 1, scale: 1, y: 0, duration: 0.6, ease: "power3.out" }, s17 + 0.3);
  rise("#b17-badge-copy", C.b17_dream, { y: 18 });
  tl.to("#b17-badge", { y: 18, duration: 0.55, ease: "power2.out" }, C.b17_not);
  draw("#b17-baseline", C.b17_not, 0.5);
  rise("#b17-l2", C.b17_not + 0.2, { y: 18 });
  tl.to("#b17-baseline", { scaleX: 1.32, duration: 0.45, ease: "power2.out" }, 110.3); // closing beat

  /* ── BEAT 18 — the paper ground rises, four ingredient cards deal in ──── */
  var s18 = start(18);
  tl.set("#b18-paper", { scaleY: 0, transformOrigin: "bottom center" }, s18);
  hide("#b18-leadin", s18);
  hide("#b18-k1, #b18-k2, #b18-k3, #b18-k4", s18, { scale: 0.95 });
  tl.set("#b18-r1, #b18-r2, #b18-r3, #b18-r4", { scaleX: 0 }, s18);
  tl.to("#b18-paper", { scaleY: 1, duration: 0.6, ease: "power3.inOut" }, s18);
  rise("#b18-leadin", C.b18_ingredients, { y: 20 });
  var b18k = ["#b18-k1", "#b18-k2", "#b18-k3", "#b18-k4"];
  var b18r = ["#b18-r1", "#b18-r2", "#b18-r3", "#b18-r4"];
  var b18c = [C.b18_people, C.b18_problems, C.b18_structure, C.b18_growth];
  b18k.forEach(function (sel, i) {
    tl.fromTo(sel, { y: 30, opacity: 0, scale: 0.95 }, { y: 0, opacity: 1, scale: 1, duration: 0.5, ease: EASE }, b18c[i]);
    draw(b18r[i], b18c[i], 0.45);
  });

  /* ── BEAT 19 — the four cards converge into one composite tile ──────────
     Full scale, so every caption stays at the 40px floor and travels inside
     its own card; the 2x2 keeps the token card-gutter on both axes, so no two
     cards can touch (owner 2026-08-03). */
  var s19 = start(19);
  tl.set("#b19-k1, #b19-k2, #b19-k3, #b19-k4", { x: 0, y: 0 }, s19);
  tl.set("#b19-tile", { opacity: 0, scale: 1.03 }, s19);
  hide("#b19-h", s19);
  // The two right-hand cards drop to the lower row BEFORE they travel left, so
  // they slide along an empty row instead of crossing the cards ahead of them —
  // no two cards ever share space, mid-move or at rest. Both rows finish their
  // vertical move in the same 1.5s window: the slide may only start once the
  // full 420px row separation exists, which clears the 396px card height with
  // the token 24px gutter. A slower rise here re-opens a corner overlap.
  tl.to("#b19-k1, #b19-k2", { y: -208, duration: 1.5, ease: "power2.inOut" }, C.b19_dream);
  tl.to("#b19-k3, #b19-k4", { y: 212, duration: 1.5, ease: "power2.inOut" }, C.b19_dream);
  tl.to("#b19-k3, #b19-k4", { x: -852, duration: 2.9, ease: "power2.inOut" }, C.b19_dream + 1.5);
  rise("#b19-h", C.b19_they, { y: 22 });
  tl.to("#b19-tile", { opacity: 1, duration: 0.45, ease: "power2.out" }, C.b19_ingredients);
  tl.to("#b19-tile", { scale: 1, duration: 0.5, ease: "power2.out" }, 125.5); // closing beat

  /* ── BEAT 20 — blue wipes in from the left, two lanes ─────────────────── */
  var s20 = start(20);
  tl.set("#b20-blue", { x: -1920 }, s20);
  hide("#b20-l1, #b20-l2", s20);
  hide("#b20-figure", s20, { y: 20 });
  hide("#b20-spark", s20, { scale: 0.7 });
  hide("#b20-dots .dot", s20, { scale: 0.6 });
  tl.to("#b20-blue", { x: 0, duration: 0.7, ease: "power3.inOut" }, s20);
  tl.to("#b20-figure", { opacity: 1, y: 0, duration: 0.6, ease: EASE }, s20 + 0.45);
  rise("#b20-l1", C.b20_reflection, { y: 20 });
  tl.to("#b20-spark", { opacity: 1, scale: 1, duration: 0.5, ease: "back.out(1.4)" }, C.b20_ai1);
  tl.to("#b20-dots .dot", { opacity: 1, scale: 1, duration: 0.3, stagger: 0.08, ease: "power2.out" }, C.b20_in);
  rise("#b20-l2", C.b20_ai2, { y: 20 });

  /* ── BEAT 21 — the highlighter sweep, three marks noticed ─────────────── */
  var s21 = start(21);
  hide("#b21-cap", s21);
  hide("#b21-marks .mark", s21);
  tl.set("#b21-marks .mark", { backgroundColor: NAVY }, s21);
  hide("#b21-figure", s21);
  tl.set("#b21-highlighter", { x: 0, opacity: 0.3 }, s21);
  tl.to("#b21-marks .mark", { opacity: 0.3, duration: 0.45, stagger: 0.05 }, C.b21_it);
  tl.to("#b21-figure", { opacity: 0.55, duration: 0.6, ease: "power2.out" }, C.b21_it + 0.2);
  rise("#b21-cap", C.b21_notice, { y: 20 });
  tl.to("#b21-highlighter", { x: 2260, duration: C.b21_you - C.b21_notice + 0.06, ease: "none" }, C.b21_notice);
  tl.to("#b21-mk1", { backgroundColor: GOLD, opacity: 1, duration: 0.4 }, C.b21_you);
  tl.to("#b21-mk2", { backgroundColor: GOLD, opacity: 1, duration: 0.4 }, C.b21_you + STAG);
  tl.to("#b21-mk3", { backgroundColor: GOLD, opacity: 1, duration: 0.4 }, C.b21_you + STAG * 2);
  tl.to("#b21-mk3", { scale: 1.35, duration: 0.22, ease: "power2.out" }, C.b21_own); // closing beat
  tl.to("#b21-mk3", { scale: 1, duration: 0.28, ease: "power2.inOut" }, C.b21_own + 0.22);

  /* ── BEAT 22 — the portrait sharpens ──────────────────────────────────── */
  var s22 = start(22);
  tl.set("#b22-paper", { scaleX: 0, transformOrigin: "left center" }, s22);
  tl.set("#b22-soft", { opacity: 0.55 }, s22);
  tl.set("#b22-crisp", { opacity: 0 }, s22);
  tl.set("#b22-contour", { scaleX: 0 }, s22);
  hide("#b22-line", s22);
  tl.to("#b22-paper", { scaleX: 1, duration: 0.6, ease: "power3.inOut" }, s22);
  tl.to("#b22-soft", { opacity: 0, duration: C.b22_describe - s22, ease: "power2.inOut" }, s22);
  tl.to("#b22-crisp", { opacity: 1, duration: C.b22_describe - s22, ease: "power2.inOut" }, s22);
  rise("#b22-line", C.b22_describe, { y: 22 });
  draw("#b22-contour", C.b22_started, 0.5); // closing beat

  /* ── BEAT 23 — navy closes in from four edges, series lockup ──────────── */
  var s23 = start(23);
  tl.set("#b23-close-t", { yPercent: -100 }, s23);
  tl.set("#b23-close-b", { yPercent: 100 }, s23);
  tl.set("#b23-close-l", { xPercent: -100 }, s23);
  tl.set("#b23-close-r", { xPercent: 100 }, s23);
  tl.set("#b23-ground", { opacity: 0 }, s23);
  hide("#b23-mark", s23, { scale: 0.9 });
  hide("#b23-brandline", s23);
  hide("#b23-cta", s23);
  tl.set("#b23-rule", { scaleX: 0, transformOrigin: "left center" }, s23);
  tl.to("#b23-close-t, #b23-close-b", { yPercent: 0, duration: 0.5, ease: "power3.inOut" }, s23);
  tl.to("#b23-close-l, #b23-close-r", { xPercent: 0, duration: 0.5, ease: "power3.inOut" }, s23);
  tl.to("#b23-ground", { opacity: 1, duration: 0.2 }, s23 + 0.5);
  tl.to("#b23-brandline", { opacity: 0.75, duration: 0.4 }, s23 + 0.1);
  tl.to("#b23-mark", { opacity: 1, scale: 1, duration: 0.55, ease: "back.out(1.4)" }, s23 + 0.5);
  // closing beat 145.58: the gold rule completes the draw it began at 142.90
  tl.to("#b23-rule", { scaleX: 1, duration: C.b23_easier - C.b23_clarity, ease: "power1.inOut" }, C.b23_clarity);
  rise("#b23-cta", C.b23_next, { y: 22 });

  return tl;
};
